pool: OT14DeployPool

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/client/opp2'
      api_location: ''
      output_location: ''
    env:
      azure_static_web_apps_api_token: $(deployment_token)
