# File: deployVars.yml
variables:
  artifactLocation: navinet-npm-feature
  azureSubscription: nn-dev-ot14
  storageAccount: nndevot14opp2sa
  resourceGroup: nn-dev-ot14-rg
  apiRoot: https://nndevot14opp2sa.z13.web.core.windows.net